version: "3.2"
services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=dietPlan
      - MYSQL_ROOT_PASSWORD=coderslab
    ports:
      - '3307:3306'
    volumes:
      - db:/var/lib/mysql
      - ./init/schema.sql:/docker-entrypoint-initdb.d/1.sql
      - ./init/data.sql:/docker-entrypoint-initdb.d/2.sql
volumes:
  db:
    driver: local