version: "3.2"
services:
  my-app:
    image: registry.gitlab.com/karolinawisniewska/dockertest/java/allyouneedisdietplan:v3
    restart: always
    container_name: my-app-driver
    ports:
      - "9090:9090"
    environment:
      - spring.datasource.url=jdbc:mysql://db:3306/dietPlan?serverTimezone=UTC
      - "MEDIA_SERVER_HOST=kurento"
      - "MEDIA_SERVER_PORT=8888"
    depends_on:
      - db
      - kurento
    volumes:
      - .m2:/root/.m2

  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    container_name: db
    command: --default-authentication-plugin=mysql_native_password --init-file /data/application/init.sql
    restart: always
    environment:
      MYSQL_DATABASE: driver
      MYSQL_ROOT_PASSWORD: coderslab
    ports:
      - "3308:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./init/schema.sql:/data/application/init.sql

  kurento:
    image: kurento/kurento-media-server:7.0.0
    restart: always
    expose:
      - "8888"
    ports:
      - "8888:8888"
    container_name: kurento

volumes:
  db-data:
    driver: local