version: "3.2"
services:
  my-app:
    build: .
#    image: registry.gitlab.com/karolinawisniewska/dockertest/java/allyouneedisdietplan:v2
    restart: always
    container_name: my-app
    ports:
      - "9090:9090"
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/dietPlan?serverTimezone=UTC
      - "MEDIA_SERVER_HOST=kurento"
      - "MEDIA_SERVER_PORT=8888"
    depends_on:
      - mysqldb
      - kurento
    volumes:
      - .m2:/root/.m2
    networks:
      - default

  mysqldb:
    image: mysql:8.0
    container_name: mysqldb
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: dietPlan
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_ROOT_PASSWORD: coderslab

  kurento:
    image: kurento/kurento-media-server:7.0.0
    restart: always
    expose:
      - "8888"
    ports:
      - "8888:8888"
    container_name: kurento
#    network_mode: host
    networks:
      - default

networks:
  default:
    ipam:
      config:
        - subnet: 172.18.1.0/24

