version: "3.2"
services:
  my-app:
#    build: .
    image: registry.gitlab.com/karolinawisniewska/dockertest/java/allyouneedisdietplan:v2
    restart: always
    container_name: my-app
    ports:
      - "9090:9090"
    environment:
      - spring.datasource.url=jdbc:mysql://db:3306/dietPlan?serverTimezone=UTC
      - "MEDIA_SERVER_HOST=kurento"
      - "MEDIA_SERVER_PORT=8888"
    depends_on:
      - db
      - kurento
    volumes:
      - .m2:/root/.m2

  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    container_name: db
    restart: always
    environment:
      MYSQL_DATABASE: dietPlan
      MYSQL_ROOT_PASSWORD: coderslab
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "3307:3306"
    volumes:
      - db:/var/lib/mysql/
      - ./init/import.sql:/docker-entrypoint-initdb.d/import.sql

  kurento:
    image: kurento/kurento-media-server:7.0.0
    restart: always
    expose:
      - "8888"
    ports:
      - "8888:8888"
    container_name: kurento

volumes:
  db:
    driver: local
