server:
  port: 9090
  ssl:
    key-store: classpath:keystore.jks
    key-store-password: kurento
    key-store-type: JKS
    key-alias: kurento-selfsigned
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dietPlan?serverTimezone=UTC
    username: root
    password: coderslab
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    root: INFO
    org:
      apache: WARN
      springframework: WARN
      kurento: INFO