server:
  port: 9090
  ssl:
    key-store: classpath:keystore.jks
    key-store-password: kurento
    key-store-type: JKS
    key-alias: kurento-selfsigned
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:3306/dietPlan?serverTimezone=UTC
    username: root
    password: coderslab
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
logging:
  level:
    root: INFO
    org:
      apache: WARN
      springframework: WARN
      kurento: INFO
project:
  name: AllYouNeedIsDietPlan
  version: 0.0.1-SNAPSHOT
edamam:
  url: https://api.edamam.com/api/recipes/v2?
  params:
    - name: type
      value: public
    - name: app_id
      value: ${APP_ID}
    - name: app_key
      value: ${APP_KEY}
    - name: random
      value: true
  fields:
    - value: label
    - value: shareAs
    - value: externalId
  precision: 0.05